server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: root
    password: Nayakenz123#
  jpa:

    hibernate.ddl-auto: create
    show-sql: true
    generate-ddl: true